<h1>Blog</h1>

<p>
    <a href="<?php echo $this->url('blog', ['action' => 'add']); ?>">Add a new blog</a>
</p>
<table class="table">
    <tr>
        <th>Title</th>
        <th>Text</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($posts as $post) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($post->getTitle()); ?></td>
            <td><?php echo $this->escapeHtml($post->getText()); ?></td>
            <td>
                <a href="<?php echo $this->url('blog/edit', [
                    'action' => 'edit',
                    'id'     => $post->getId()
                ]); ?>">Edit</a>
                <a href="<?php echo $this->url('blog/delete', [
                    'action' => 'delete',
                    'id'     => $post->getId()
                ]); ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>